import { Venue } from "@prisma/client";

export const initVenue: Venue = {
	mask: "",
	accessibility: "🧐",
	name: "First Unitarian Church",
	address: "119 Pierrepont St",
	neighborhood: "brooklyn heights",
	borough: "brooklyn",
	notes: "",
	entry: "",
	restroom: "",
	seating: "",
	stage: "",
	transit: "",
	link: "",
	confirmed: "email",
	maskPolicy: "",
	phoneNumber: "",
	age: "",
	createdAt: new Date,
	email: "",
	ofNoteWaitTime: "",
	id: 0,
	the: "",
	asl: "",
	listeningDevices: "",
	visualAids: "",
};
